<a href="https://colab.research.google.com/github/HuyenNguyenHelen/INFO5731-Spring24/blob/main/Lecture1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mounting Drive


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!ls '/content/drive'

MyDrive


In [ ]:
!ls '/content/drive/MyDrive/0_examples'

hello.py


In [ ]:
!python3 '/content/drive/MyDrive/0_examples/hello.py'

Hello the world! This is a test.


# Add a form

In [ ]:
# @title Default title text
sleeptime = 4 # @param {type:"integer"}


In [ ]:
# @title Default title text
color = "green" # @param ["red", "green", "blue"]


In [ ]:
# @title Default title text
date = "2024-01-20" # @param {type:"date"}


#Pandas

In [ ]:
import pandas as pd
import numpy as np

## Creating

In [ ]:
s = pd.Series([1,2,3,4, np.nan, 6,8])
print(s)

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    6.0
6    8.0
dtype: float64


In [ ]:
dates = pd.date_range('20240115', periods = 6)
dates

DatetimeIndex(['2024-01-15', '2024-01-16', '2024-01-17', '2024-01-18',
               '2024-01-19', '2024-01-20'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(6,4), index = dates, columns=['A', 'B', 'C', 'D'])
df

A         B         C         D
2024-01-15  1.292647  0.425665  0.069267  1.372403
2024-01-16 -0.390573 -0.543710  2.774666 -0.196762
2024-01-17  0.623659 -0.599539  0.413038 -1.560600
2024-01-18 -0.650564  0.212652  0.007418 -0.737086
2024-01-19  0.737877  0.564739 -0.750450  0.384043
2024-01-20  2.236482  0.310860  1.414815  0.347021

## Viewing


In [ ]:
df.head()

A         B         C         D
2024-01-15  0.886027 -0.790775  0.019563 -0.254894
2024-01-16  0.938388 -0.354453  0.853559 -0.046939
2024-01-17 -0.898663 -0.362303 -0.963495 -0.398642
2024-01-18  0.633273 -0.066117  0.625101 -0.426385
2024-01-19 -2.134070 -0.511352  0.798709  0.037987

In [ ]:
df.tail()

A         B         C         D
2024-01-16  0.938388 -0.354453  0.853559 -0.046939
2024-01-17 -0.898663 -0.362303 -0.963495 -0.398642
2024-01-18  0.633273 -0.066117  0.625101 -0.426385
2024-01-19 -2.134070 -0.511352  0.798709  0.037987
2024-01-20 -0.407366 -1.198974 -1.841724  0.827455

In [ ]:
df.index

DatetimeIndex(['2024-01-15', '2024-01-16', '2024-01-17', '2024-01-18',
               '2024-01-19', '2024-01-20'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [ ]:
df.values

array([[ 0.88602745, -0.7907746 ,  0.01956302, -0.25489363],
       [ 0.93838821, -0.35445315,  0.853559  , -0.0469389 ],
       [-0.89866287, -0.36230331, -0.96349471, -0.39864181],
       [ 0.63327288, -0.06611677,  0.62510139, -0.42638544],
       [-2.13406967, -0.5113519 ,  0.7987093 ,  0.03798689],
       [-0.40736572, -1.19897399, -1.84172434,  0.82745476]])

In [ ]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.163735 -0.547329 -0.084714 -0.043570
std    1.219311  0.397040  1.098621  0.465323
min   -2.134070 -1.198974 -1.841724 -0.426385
25%   -0.775839 -0.720919 -0.717730 -0.362705
50%    0.112954 -0.436828  0.322332 -0.150916
75%    0.822839 -0.356416  0.755307  0.016755
max    0.938388 -0.066117  0.853559  0.827455

In [ ]:
df.T

2024-01-15  2024-01-16  2024-01-17  2024-01-18  2024-01-19  2024-01-20
A    0.886027    0.938388   -0.898663    0.633273   -2.134070   -0.407366
B   -0.790775   -0.354453   -0.362303   -0.066117   -0.511352   -1.198974
C    0.019563    0.853559   -0.963495    0.625101    0.798709   -1.841724
D   -0.254894   -0.046939   -0.398642   -0.426385    0.037987    0.827455

In [ ]:
df.sort_index(axis = 0, ascending=False)

A         B         C         D
2024-01-20 -0.407366 -1.198974 -1.841724  0.827455
2024-01-19 -2.134070 -0.511352  0.798709  0.037987
2024-01-18  0.633273 -0.066117  0.625101 -0.426385
2024-01-17 -0.898663 -0.362303 -0.963495 -0.398642
2024-01-16  0.938388 -0.354453  0.853559 -0.046939
2024-01-15  0.886027 -0.790775  0.019563 -0.254894

In [ ]:
df.sort_values(by='B')

A         B         C         D
2024-01-20 -0.407366 -1.198974 -1.841724  0.827455
2024-01-15  0.886027 -0.790775  0.019563 -0.254894
2024-01-19 -2.134070 -0.511352  0.798709  0.037987
2024-01-17 -0.898663 -0.362303 -0.963495 -0.398642
2024-01-16  0.938388 -0.354453  0.853559 -0.046939
2024-01-18  0.633273 -0.066117  0.625101 -0.426385

## Selection

In [ ]:
df['A']

2024-01-15    0.886027
2024-01-16    0.938388
2024-01-17   -0.898663
2024-01-18    0.633273
2024-01-19   -2.134070
2024-01-20   -0.407366
Freq: D, Name: A, dtype: float64

In [ ]:
df['2024-01-18':]

A         B         C         D
2024-01-18  0.633273 -0.066117  0.625101 -0.426385
2024-01-19 -2.134070 -0.511352  0.798709  0.037987
2024-01-20 -0.407366 -1.198974 -1.841724  0.827455

In [ ]:
df.loc[dates[0]] # 2024-01-15

A    0.886027
B   -0.790775
C    0.019563
D   -0.254894
Name: 2024-01-15 00:00:00, dtype: float64

In [ ]:
df.iloc[0]

A    0.886027
B   -0.790775
C    0.019563
D   -0.254894
Name: 2024-01-15 00:00:00, dtype: float64

In [ ]:
df.iloc[:3]

A         B         C         D
2024-01-15  0.886027 -0.790775  0.019563 -0.254894
2024-01-16  0.938388 -0.354453  0.853559 -0.046939
2024-01-17 -0.898663 -0.362303 -0.963495 -0.398642

In [ ]:
# Boolean condition
df[df>0]

A   B         C         D
2024-01-15  0.886027 NaN  0.019563       NaN
2024-01-16  0.938388 NaN  0.853559       NaN
2024-01-17       NaN NaN       NaN       NaN
2024-01-18  0.633273 NaN  0.625101       NaN
2024-01-19       NaN NaN  0.798709  0.037987
2024-01-20       NaN NaN       NaN  0.827455

## Merge

In [ ]:
pieces=[df[:2], df[3:5], df[5:]]
pieces

[                   A         B         C         D
 2024-01-15  0.886027 -0.790775  0.019563 -0.254894
 2024-01-16  0.938388 -0.354453  0.853559 -0.046939,
                    A         B         C         D
 2024-01-18  0.633273 -0.066117  0.625101 -0.426385
 2024-01-19 -2.134070 -0.511352  0.798709  0.037987,
                    A         B         C         D
 2024-01-20 -0.407366 -1.198974 -1.841724  0.827455]

In [ ]:
pd.concat(pieces)

A         B         C         D
2024-01-15  0.886027 -0.790775  0.019563 -0.254894
2024-01-16  0.938388 -0.354453  0.853559 -0.046939
2024-01-18  0.633273 -0.066117  0.625101 -0.426385
2024-01-19 -2.134070 -0.511352  0.798709  0.037987
2024-01-20 -0.407366 -1.198974 -1.841724  0.827455

In [ ]:
left = pd.DataFrame({'key': ['foo', 'fin'], 'lval': [1,2]})
right = pd.DataFrame({'key': ['foo', 'fin'], 'rval': [3,4]})
print(left)
print(right)

   key  lval
0  foo     1
1  fin     2
   key  rval
0  foo     3
1  fin     4


In [ ]:
pd.merge(left, right, on='key')

key  lval  rval
0  foo     1     3
1  fin     2     4

# Numpy

### Create arrays, matrices

In [ ]:
import numpy as np
A = np.array([[1,2,3], [4,5,6]])
Af = np.array([1,2,3], float)
print(A)
print(Af)

[[1 2 3]
 [4 5 6]]
[1. 2. 3.]


In [ ]:
np.random.random((2, 3))

array([[0.59902441, 0.80708203, 0.62870771],
       [0.22858115, 0.61330522, 0.31844247]])

In [ ]:
# Draw random samples from a normal (Gaussian) distribution, with a mean=1, and std=2.
a = np.random.normal(loc=1.0, scale = 2.0, size = (2,2))
a

array([[-1.39695289,  0.87629342],
       [ 1.49709115, -0.13881027]])

In [ ]:
# Save and load a sample to/from a txt file
np.savetxt('a_out.txt', a)
b = np.loadtxt('a_out.txt')
b

array([[-1.39695289,  0.87629342],
       [ 1.49709115, -0.13881027]])

In [ ]:
# Array is mutable
A = np.zeros((2,2))
print('A: \n', A)
C = A
print('C: \n', C)
C[0,0]=1
A

A: 
 [[0. 0.]
 [0. 0.]]
C: 
 [[0. 0.]
 [0. 0.]]


array([[1., 0.],
       [0., 0.]])

In [ ]:
# Return evenly spaced numbers over a specified interval.
print(np.arange(0, 1, 0.2))

print(np.linspace(0, 2*np.pi, 4))


[0.  0.2 0.4 0.6 0.8]
[0.         2.0943951  4.1887902  6.28318531]


In [ ]:
# Slicing array
a = np.random.random((4,5))
a


array([[0.59645996, 0.37665495, 0.63934431, 0.66754458, 0.67892573],
       [0.91330382, 0.99363498, 0.41136683, 0.60568141, 0.74589459],
       [0.40003813, 0.40349554, 0.43087777, 0.01690147, 0.04021017],
       [0.3218524 , 0.19382361, 0.59883864, 0.21899246, 0.39766121]])

In [ ]:
a[2, :]

array([0.40003813, 0.40349554, 0.43087777, 0.01690147, 0.04021017])

In [ ]:
a[1:3, :]

array([[0.91330382, 0.99363498, 0.41136683, 0.60568141, 0.74589459],
       [0.40003813, 0.40349554, 0.43087777, 0.01690147, 0.04021017]])

In [ ]:
a[:, 2:4]

array([[0.63934431, 0.66754458],
       [0.41136683, 0.60568141],
       [0.43087777, 0.01690147],
       [0.59883864, 0.21899246]])

### Attribute, arithmetic, vector

In [ ]:
a = np.arange(10).reshape((2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a.shape

(2, 5)

In [ ]:
a.size

10

In [ ]:
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
# math operatio n
a = np.arange(4)
b = np.array([2,3,2,4])
a

array([0, 1, 2, 3])

In [ ]:
# element-wise mul
a*b

array([ 0,  3,  4, 12])

In [ ]:
b-a

array([2, 2, 0, 1])

In [ ]:
# numpy automatically convert lists into np array
c = [2,3,4,5]
a*c

array([ 0,  3,  8, 15])

In [ ]:
u = [1,2,3]
v = [1,1,1]
np.inner(u,v)

6

In [ ]:
np.outer(u,v)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
np.dot(u,v)

6

### Array broadcasting
Use slides 43
Array broadcasting means that when operating on two arrays, numpy compares shapes.
Two dimensions are compatible when (1) they are of equal size and (2) one of them is 1. This also allows us to add a constant to a matrix or multiply a matrix by a constant.

In [ ]:
A = np.ones((3,3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
3*A-1

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

### Matrix operation

In [ ]:
A = np.ones((3,2))
A

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
A.T

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
B = np.ones((2,3))
B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.dot(A, B)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
# 2D x 2D, then it's matrix product, using matmul is more prefered
np.matmul(A, B)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
np.dot(B,A)

array([[3., 3.],
       [3., 3.]])

### Array operaation

In [ ]:
a = np.random.random((2,3))
a

array([[0.92935279, 0.04800898, 0.7617234 ],
       [0.19584514, 0.04107727, 0.52332937]])

In [ ]:
a.sum()

2.4993369502907097

In [ ]:
a.sum(axis = 0)

array([1.12519793, 0.08908625, 1.28505277])

In [ ]:
a.sum(axis=1)

array([2.08361065, 1.08791961])

In [ ]:
# accumulative sum
a.cumsum()

array([0.96074247, 1.48460993, 2.08361065, 2.15240902, 2.83586098,
       3.17153026])

In [ ]:
# accumulative sum over row
print(a.cumsum(axis=1))
# accumulative sum over column
print(a.cumsum(axis=0))


[[0.96074247 1.48460993 2.08361065]
 [0.06879837 0.75225032 1.08791961]]
[[0.96074247 0.52386746 0.59900073]
 [1.02954084 1.20731941 0.93467001]]


### Iterating over arrays

In [ ]:
a = np.arange(6)
a = a.reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
for x in np.nditer(a):
  print(x)

0
1
2
3
4
5


In [ ]:
for x in np.nditer(a.T):
  print(x)

0
1
2
3
4
5


In [ ]:
for x in np.nditer(a, order='F'):
  print(x)

0
3
1
4
2
5


In [ ]:
for x in np.nditer(a, order='C'):
  print(x)

0
1
2
3
4
5


In [ ]:
for x in np.nditer(a, order='K'):
  print(x)

0
1
2
3
4
5


### Indexing

In [ ]:
a = np.arange(15).reshape((3,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a[2]

array([10, 11, 12, 13, 14])

In [ ]:
a[2, :]

array([10, 11, 12, 13, 14])

In [ ]:
it = np.nditer(a, flags = ['c_index'])
while not it.finished:
  print('%d <%d>' %(it[0], it.index), it.iternext())

0 <0> True
1 <1> True
2 <2> True
3 <3> True
4 <4> True
5 <5> True
6 <6> True
7 <7> True
8 <8> True
9 <9> True
10 <10> True
11 <11> True
12 <12> True
13 <13> True
14 <14> False


In [ ]:
a = np.arange(15).reshape((3,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
i = np.array([[0,1], [1,2]]) # to specify row indices
j = np.array([[2,1], [4,4]]) # to specify column indices
a[i]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [ ]:
i = np.array([[0,1], [1,2]]) # to specify row indices
j = np.array([[2,1], [4,4]]) # to specify column indices
a[i, j]

array([[ 2,  6],
       [ 9, 14]])